# 锚点系统配置文件

settings:
  # 传送冷却时间（秒）
  cooldown-time: 120
  
  # 锚点解锁范围（方块）
  unlock-radius: 3
  
  # 解锁声音设置
  unlock-sound: BLOCK_ENCHANTMENT_TABLE_USE
  unlock-sound-volume: 10.0
  unlock-sound-pitch: 1.0

# 数据存储设置
storage:
  # 数据文件名
  filename: 'landmarks.yml'

# 消息设置
messages:
  prefix: '<gradient:gold:yellow>[魔法锚点]</gradient> '
  landmark-not-exist: '<gradient:red:dark_red>✧ 魔法师,这个锚点似乎并不存在于这个世界...</gradient>'
  landmark-not-unlocked: '<gradient:red:dark_red>✧ 魔法师,你需要先解开这个锚点的封印才能使用它!</gradient>'
  teleport-cooldown: '<gradient:red:dark_red>✧ 魔法师,传送魔法还在冷却中,需要等待 <time> 秒才能再次施法...</gradient>'
  teleport-success: '<gradient:green:dark_green>✧ 魔法师成功施展传送术,抵达了锚点 <landmark>!</gradient>'
  teleport-failed: '<gradient:red:dark_red>✧ 糟糕,传送魔法施展失败了!</gradient>'
  unlock-title: '<gradient:gold:yellow>✧ 新的魔法锚点解封了!</gradient>'
  unlock-subtitle: '<white><landmark_name></white>'
  unlock-message: '<gradient:green:aqua>✧ 魔法师解开了锚点 <gold><landmark_name></gold> 的封印!</gradient>'
  command-player-only: '<gradient:red:dark_red>✧ 抱歉,只有魔法师才能使用这个咒语!</gradient>'
  command-usage: '<gradient:red:dark_red>✧ 魔法师,咒语的正确用法是: <usage></gradient>'
  create-success: '<gradient:green:aqua>✧ 魔法师成功创造了新的锚点 <gold><name></gold>!</gradient>'
  delete-success: '<gradient:green:aqua>✧ 魔法师成功抹除了锚点 <gold><name></gold>!</gradient>'
  edit-success: '<gradient:green:aqua>✧ 魔法师修改了锚点 <gold><name></gold> 的描述!</gradient>'
  rename-success: '<gradient:green:aqua>✧ 魔法师将锚点从 <gold><old_name></gold> 重命名为 <gold><new_name></gold>!</gradient>'
  reload-success: '<gradient:green:aqua>✧ 魔法书重新加载完成!</gradient>'
  reload-failed: '<gradient:red:dark_red>✧ 魔法书加载失败!请检查魔法记录。</gradient>'
  not-at-landmark: '<gradient:red:dark_red>✧ 魔法师,你需要站在锚点范围内才能施展传送术!</gradient>'
  help:
    separator: '<gradient:gold:yellow>✧══════════ 魔法锚点咒语书 ══════════✧</gradient>'
    command: '%prefix% <yellow>%command%</yellow>'
  landmark-exists: '<gradient:red:dark_red>✧ 魔法师,这个锚点名称已被占用了!</gradient>'
  create-title: '<gradient:gold:yellow>✧══════════ 魔法锚点 ══════════✧</gradient>'
  create-subtitle: '<gradient:green:aqua>成功创造新的锚点!</gradient>'
  delete-title: '<gradient:red:dark_red>✧══════════ 魔法锚点 ══════════✧</gradient>'
  delete-subtitle: '<gradient:red:dark_red>锚点已被抹除!</gradient>'
  rename-title: '<gradient:gold:yellow>✧══════════ 魔法锚点 ══════════✧</gradient>'
  rename-subtitle: '<gradient:green:aqua>锚点重命名成功!</gradient>'
  
# GUI设置
gui:
  title: '<#c7a3ed><bold>✧ 魔法锚点系统 ✦</bold>'
  size: 45
  border:
    material: BLACK_STAINED_GLASS_PANE
    name: ' '
  items:
    current:
      material: CONDUIT
      locked_material: BARRIER
    unlocked:
      material: AMETHYST_SHARD
      name: '<#c7a3ed><bold>%landmark_name%</bold>'
      glow: true
    locked:
      material: BARRIER
      name: '<gray><bold>%landmark_name%</bold>'
  lore:
    world: '<#c7a3ed><bold>• 位置</bold> <white><bold>%world%</bold>'
    coordinates: '<#c7a3ed><bold>• 坐标</bold> <white><bold>%x% %y% %z%</bold>'
    description: '<#c7a3ed><bold>• 描述</bold> <white><bold>%description%</bold>'
    click-teleport: '<#c7a3ed><bold>▸ 点击传送</bold>'
    locked-coordinates: '<#c7a3ed><bold>• 坐标</bold> <gray><bold>未知</bold>'
    locked-description: '<#c7a3ed><bold>• 描述</bold> <gray><bold>未知</bold>'
    locked: '<gray><bold>该锚点尚未解封</bold>'
    separator: '<#c7a3ed><bold>﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍</bold>'
  current-location:
    at-landmark: |
      <#c7a3ed><bold>✦ %landmark_name%</bold>
      <white><bold>当前所在位置</bold>
    not-at-landmark: |
      <#c7a3ed><bold>✦ 未解锁区域</bold>
      <white><bold>需要站在已解锁的锚点处</bold>

# 粒子效果设置
particles:
  # 五角星魔法阵
  center:
    enabled: true
    type: END_ROD           
    height: 0.1             
    star_radius: 1.5        
    circle_radius: 2.0      
    particle_density: 0.3   # 增加基础密度间隔
    animation:
      duration: 4.0        
      fade_in: 1.0         
      stay: 2.0           
      fade_out: 1.0        
  
  # 边界光柱
  border:
    enabled: true
    type: SPELL_WITCH       
    height: 1.5            # 降低高度
    density: 0.03          # 增加密度
    spiral_speed: 1.0      # 降低速度使旋转更平滑
    trail_length: 1.5      # 增加尾巴长度
    head_density: 6        # 增加头部密度
    spiral_count: 8        # 增加螺旋数量
    spiral_radius: 0.3     # 控制螺旋半径
    display-range: 32 